### ISSUE TITLE
Run Jest executes node instead of shell script

### ISSUE THREAD

**Issue by fjc0k** [firsttris/vscode-jest-runner#119]
Click `Run` button:

```bash
node '*****/node_modules/.bin/jest' '*****/src/components/button/button.test.tsx' -t 'ok'
```

The errors throw:

```bash
*****/node_modules/.bin/jest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
```

The `*****/node_modules/.bin/jest` file:

```bash
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

export NODE_PATH="*********"
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../jest/bin/jest.js" "$@"
else 
  exec node  "$basedir/../jest/bin/jest.js" "$@"
fi
```

Maybe it's because The package manager I'm using is [pnpm](https://pnpm.js.org/).

**Comment by firsttris** [comment]
i guess that's related to pnpm

**Comment by axmrnv** [comment]
That's not related to any specific package manager. Look at the command vscode-jest-runner tries to run:

```sh
node '***/node_modules/.bin/jest' '***/filename.spec.ts' -t 'test-name'
```

Here, `node_modules/.bin/jest` is a shell script (#!/bin/sh) and `node` is looking for js file to execute. If you omit `node` and run jest directly from the console, it will run ok:

```sh
'***/node_modules/.bin/jest' '***/filename.spec.ts' -t 'test-name'
```

However, this is not possible, since ["node" is hardcoded](https://github.com/firsttris/vscode-jest-runner/blob/8eb52f4faff398268239faef06380904dd36cb10/src/jestRunnerConfig.ts#L23) in the JestRunnerConfig and is used with default scripts.

As a workaround, you can force using js version of jest by specifying

```json
"jestrunner.jestPath": "node_modules/jest/bin/jest.js"
```

in your `.vscode/settings.json` file.

**Comment by Mattinton** [comment]
If you're using create-react-app `node_modules/react-scripts/scripts/test.js` as your jestPath worked for me

**Comment by zkochan** [comment]
> As a workaround, you can force using js version of jest by specifying
> "jestrunner.jestPath": "node_modules/jest/bin/jest.js"

This is the right solution.

pnpm creates shell files on all systems. npm and yarn create the shell files on Windows. So in a way, pnpm is more consistent. The described issue will happen with npm/yarn as well on Windows systems.

**Comment by tjx666** [comment]
I think this issue should deal by extension not force user to set it.

**Comment by gengjiawen** [comment]
Always use `'node_modules/jest/bin/jest.js'` should fix this issue ? @firsttris Is this okay ? I can send a PR if you like.

https://github.com/firsttris/vscode-jest-runner/blob/2401fa16e28d4ada4b4c3861706c84ea177c2655/src/jestRunnerConfig.ts#L41

**Comment by Hental** [comment]
i send a PR #144 for fix this
