### ISSUE TITLE
Avoid changing directory on run/debug

### ISSUE THREAD

**Issue by lwillmeth** [firsttris/vscode-jest-runner#124]
My vscode workspace is a directory with several repos.  When I click run/debug, vscode-jest-runner first changes directory out of the current repo, then fails to run the test, because it's in the wrong directory.

Is there a flag I can use to avoid changing directories?  The open terminal was already in the correct directory.

My only jestrunner setting is: `"jestrunner.jestCommand": "npm run test --"`

**Comment by firsttris** [comment]
i see, so the folder you open with vscode contains multiple repo and in those repos there is an jest.config.js and the jest binary correct?

**Comment by lwillmeth** [comment]
Yes, my vscode directory structure is like `/company/microservice/`, but using Jest Runner from a test in `microservice` immediately cd's back to /company, then fails.

Just for kicks I tried adding `jestrunner.projectPath: microservice` as a potential temporary solution, but it looked for jest in `/company/microservice/microservice/...`

This is my first time using Jest Runner so I may be overlooking an obvious 'right' way to do this, and if not, thanks anyway.  Appreciate your efforts on this project.

**Comment by jtinbergen** [comment]
We are in the same boat: /project/microservice/__test__/integration.test.js runs/debugs tests from the __test__ folder which has different effects then running test from the microservice root (where the package.json and jest config is/are).

**Comment by firsttris** [comment]
yea i think this feature is currently missing, we had almost implemented it but had to revert.
https://github.com/firsttris/vscode-jest-runner/pull/111

i think we would need some very clever dynamic reverse lookup for the jest binary, add find out the correct folder.

currently we always jump to the workspace folder.

happy about any pull request.

**Comment by jvassev** [comment]
I've hit  similar problem because there are config/support files in the current directory (where a service resides in a subdir in a monorepo and has its own jest config). Without the plugin I'd first `cd` to the service dir and run jest. I wanted to keep the same workflow and also use this very handy plugin!

This patch https://github.com/firsttris/vscode-jest-runner/pull/133 first navigates to the parent folder of the `jest.config.js` and then runs the test. It would still work with a one project per workspace as well in the setup I described.

**Comment by firsttris** [comment]
there is now a new algorithm to detect the correct directory with the jest binary.

and there is also an option to disable changing directory to workspace root before running the test.
