### ISSUE TITLE
Test name detection fails when we use a function to construct the test

### ISSUE THREAD

**Issue by domoritz** [firsttris/vscode-jest-runner#16]
I'm using

```
it("script-empty", assertSchema("script-empty", "MyType", `No root type "MyType" found`));
```

Which runs

```
node '/Users/domoritz/Developer/UW/ts-json-schema-generator/node_modules/.bin/jest' '/Users/domoritz/Developer/UW/ts-json-schema-generator/test/invalid-data.test.ts' -t 'it("script-empty", assertSchema("script-empty", "MyType", `No root type "MyType" found`));'
```

But instead it should run 

```
node '/Users/domoritz/Developer/UW/ts-json-schema-generator/node_modules/.bin/jest' '/Users/domoritz/Developer/UW/ts-json-schema-generator/test/invalid-data.test.ts' -t 'script-empty'
```

**Comment by firsttris** [comment]
And you right-click somwhere in "script-empty" ?

**Comment by domoritz** [comment]
Yes. My workaround is to highlight the whole word. Is this expected behavior?

**Comment by firsttris** [comment]
Both ways should work.

**Comment by firsttris** [comment]
this is the regex which is used
https://github.com/firsttris/vscode-jest-runner/blob/master/src/util.ts#L19

**Comment by firsttris** [comment]
I can reproduce your issue.

`╰─>$ nnode '/home/firsttris/Projects/someproject/packages/app/test/snapshot/formElements/FormInput.test.tsx' -t 'script-┬─[firsttris@e480:~/Projects/]─[15:27:41]root type "MyType" found'`

The issue is the Regex i postet to you.

I verified on regex101.com

![image](https://user-images.githubusercontent.com/1709260/52642515-73fa2680-2edb-11e9-8b09-46e5cb747f8e.png)

We need to update the Regex

**Comment by firsttris** [comment]
@domoritz motiviated to contribute the correct regex?

**Comment by domoritz** [comment]
Motivated yes, but won't have the headspace for the foreseeable future, sorry.

**Comment by firsttris** [comment]
same issue here :dancer:

**Comment by domoritz** [comment]
Regexes are fundamentally not powerful enough to cover all cases but I took a stab at a slightly more robust matcher: https://github.com/firsttris/vscode-jest-runner/pull/18.
