### ISSUE TITLE
(typescript) Decorated parameters result in jest-runner erroring

### ISSUE THREAD

**Issue by jbjhjm** [firsttris/vscode-jest-runner#260]
As soon as a test file contains a param decorator like e.g.

```ts
class SimpleTestController {
	handlerMethod(@Body() xxx) {
		return;
	}
}
```

jest-runner will fail.
There already was a issue report some time ago:
https://github.com/firsttris/vscode-jest-runner/issues/225

Unfortunately the issue remains. Console reported the following error:

```
jest-editor-support parser returned error SyntaxError: Decorators cannot be used to decorate parameters. (18:15)
    at mt._raise (c:\Users\Jannik\.vscode\extensions\firsttris.vscode-jest-runner-0.4.48\node_modules\@babel\parser\lib\index.js:479:22)
```

In the log paths one can see babel parser is generating this error.
It seems some of the used dependencies try to transpile typescript based on babel.

I think this is whats happening:
* https://github.com/firsttris/vscode-jest-runner/blob/master/src/JestRunnerCodeLensProvider.ts#L58
* JestRunnerCodeLensProvider parses source files using jest-editor-support.
* jest-editor-support transpiles files using babel 7 so it does not fully support typescript syntax

So if jest-editor-support is not going to implement full typescript / tsc support, typescript files should be compiled to ECMAscript before being passed to the babel-based transpiler.

**Comment by firsttris** [comment]
thx for your report.

my understanding is babel 7 parser fully supports typescript syntax. We even migrated from typescript to babel parser in jest-editor-support. for whatever reasons. but decorators are experimental (even in typescript compiler).
jest-editor-support would need to add the corresponding plugin to make decorators work. probably the plugin is missing.

since you already figured out the issue originates in jest-editor-support, we need to create the issue there to get it fixed:
https://github.com/jest-community/jest-editor-support/issues

best regards
Tristan

**Comment by firsttris** [comment]
i think its just a matter of addion the plugin here.
https://github.com/jest-community/jest-editor-support/blob/master/src/parsers/helper.ts#L11

i refactored this from typerscript to bable_parser at some point
