### ISSUE TITLE
'run jest' does nothing

### ISSUE THREAD

**Issue by samthomson** [firsttris/vscode-jest-runner#59]
Right clicking anywhere within a test and selecting 'run jest' does nothing.
If I select the test name and right click > 'run jest' it will work in most cases.

Expected behaviour: that it runs just that test.

Version: 0.4.11
vscode: 1.41.1
os: popos/ubuntu 18

**Comment by samthomson** [comment]
Happy to try and help if you're open to PRs :slightly_smiling_face:

**Comment by firsttris** [comment]
This should actually work. At least for me it does. If you just right click we create the full unique test path and do an exact match, while with a select/Highlight we Just use the test Name (Which is not unique). Im thinking about removing the regex exact match because it doesnt work for some terminals.

**Comment by firsttris** [comment]
Probably connected to https://github.com/firsttris/vscode-jest-runner/issues/57

**Comment by firsttris** [comment]
please verify and report back if your issue is solved with 0.4.12

**Comment by firsttris** [comment]
0.4.15
feel free to re-open or create a new issue if you find one.

thx for reporting this issue

**Comment by samthomson** [comment]
Hey, you were too fast for me :sweat_smile: Just updated and tested, both issues resolved. Thanks a lot :slightly_smiling_face:
