### ISSUE TITLE
Comparison with the other Jest extension for VS Code

### ISSUE THREAD

**Issue by dandv** [firsttris/vscode-jest-runner#86]
Hi, I'm new to Jest in VS Code. How is this extension different from https://github.com/jest-community/vscode-jest ?

I see the README has "The Aim", which looks like tribute to the other extension, so it would be good to explain how this one is different, so devs can make an informed choice between the two.

Maybe that will get it more popularity as well (only 51 repo stars vs. ~1900 for @jest-community's extension).

**Comment by firsttris** [comment]
hey @dandv 

my extension is about running or debugging a sepcific test, while vscode-jest is more like a integrated workflow. it runs your test-suite everytime you change it. (e.g. its not possible to run a specific test)

i will add this to readme.

about popularity, vscode-jest is a more mature extension then this one. 

It would be better to compare installs from marketplace not stars from github. because i think most people are rather installing the extensions then starring the project on github. 70k vs 400k

also i'm contributingto the jest compiler of jest-community.

**Comment by firsttris** [comment]
improved the Readme with your feedback:

https://github.com/firsttris/vscode-jest-runner/commit/472e86f31d8df2d401fc04c3166dc7c3fd6db441
