### ISSUE TITLE
Test name detection fails when using an type alias of 'it' or 'describe' such as 'test'

### ISSUE THREAD

**Issue by iPlexor** [firsttris/vscode-jest-runner#9]
Hey @firsttris, you got me thinking when you said I don't need to select the test name to run it. In my experience, not selecting it resulted in a -t "" argument, so ALL tests run.  Selecting the name and right clicking 'Run Test' was my workaround for this. 

Having just looked into it, I now see the issue. Without a selection the regex below is used to parse for the test name:
https://github.com/firsttris/vscode-jest-runner/blob/795a97aed08411ec2e27b04bbb6d9cd07b294d14/src/util.ts#L19

This regex will only find the test name if its in a 'describe' or 'it' call. But looking at Jest type definitions, theres a bunch of aliases (below) and in my project we are using 'test' instead of 'it'.
![image](https://user-images.githubusercontent.com/11964069/43669322-f782d38e-9779-11e8-8962-b84f01c781f0.png)

I'm guessing you can just OR in those other alies to cover these.

Something like this?
`const TEST_NAME_REGEX = /(describe|fdescribe|xdescribe|it|fit|xit|test|xtest)\(('|"|`)(.*)('|"|`)/; `

I'd make a PR, but I've never setup to debug an extension. If I have time I will try to setup and test this.

**Comment by firsttris** [comment]
actually the easiest way to develop & test this exention is:

to just clone this repo in the extension folder of your vscode (delete the existing vscode-jest-runner from marketplace).

open vscode two times:
- one time with you actual project (which contains your tests)
- one time the extension (vscode-jest-runner)

now in (vscode-jest-runner) you can install deps, change code of the extension, make a build, and test it in you other vscode (actual project)

after each build you just have to CTRL+P and Reload Window (in you acutal project). (otherwise vscode doesn't recognize the changes)

**Comment by firsttris** [comment]
I found that this feature is implemented now.
