### ISSUE TITLE
Symlink Path Resolution

### ISSUE THREAD

**Issue by cenk1cenk2** [firsttris/vscode-jest-runner#93]
I have a weird problem, done some searches in the issues but could not find something closer to this.

My working directory is a symlink to another place. When it tries to resolve the pattern it uses the symlinked path while it searches for it inside the original directory.

jestrunner is utilized through SSH-Remote plugin to another server in vscode-insiders 1.48.0 version. Everything else seems okay for it to run.

If there is already an issue open for this I am terribly sorry.

![image](https://user-images.githubusercontent.com/26881592/88226611-9cf41e80-cc6c-11ea-8960-c4836dde5c93.png)

**Comment by fermmm** [comment]
When you opened your project in vscode, if you navigated to the project folder using a simlink or "shortcut" or "link" (it has different names in the different distros) then your project path will be the "link" path and not the "real" path and the extension simply doesn't find the tests and you see the error: `No tests found, exiting with code 1`

So the workaround is to open the project folder again in vscode browsing the real path to the folder, after that the extension works.

The source of the problem:
This extension runs 2 commands when running a test, the first one is:
`cd <absolute path of your project>`
And the second one is:
`jest <absolute path of the test file> -t <test name>`

I don't know what is the point of doing cd when the second command uses the absolute path, what the extension should do is

`cd -P <absolute path of your project>`
`jest <relative path to the test file> -t <test name>`

Notice the -P parameter in the cd command, this parameter tells a Unix based system to go to the real path even if you are passing a "linked" path, so that also fixes the issue but needs to be implemented into the extension.

**Comment by cenk1cenk2** [comment]
Thank you for the workaround. I will close this issue since it is more related to jest then this plugin.
